pipelines:
  default:
    - step:
        name: Build and Test
        image: node:14
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm run test:unit